articles/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^show_all/$', 'articles.views.articles'),
	url(r'^(?P<article_id>\d+)/$', 'articles.views.article'),
	url(r'^(?P<article_id>\d+)/add_comment/$', 'articles.views.add_comment'),
)

notifications/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('notifications.views',
	url(r'^show/(?P<notification_id>\d+)/$', 'show_notification'),
	url(r'^delete/(?P<notification_id>\d+)/$', 'delete_notification'),
)

skcms/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	(r'^article/',include('articles.urls')),
    # Examples:
    # url(r'^$', 'skcms.views.home', name='home'),
    # url(r'^skcms/', include('skcms.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('userprofile.urls')),
    url(r'^notifications/', include('notifications.urls')),

    url(r'^accounts/login/$', 'skcms.views.login'),
    url(r'^accounts/auth/$', 'skcms.views.auth_view'),
    url(r'^accounts/logout/$', 'skcms.views.logout'),
    url(r'^accounts/loggedin/$', 'skcms.views.loggedin'),
    url(r'^accounts/invalid/$', 'skcms.views.invalid_login'),

    url(r'^accounts/create_user/$', 'skcms.views.create_user'),
    url(r'^accounts/create_user_success/$', 'skcms.views.create_user_success'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

userprofile/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^profile/$', 'userprofile.views.user_profile'),
)

articles/models.py
#-*- coding: utf-8 -*-
from django.db import models

class Article(models.Model):
	title = models.CharField(max_length=150, verbose_name="Title")
	content = models.TextField(verbose_name="Text")
	published = models.DateTimeField(verbose_name="Publication date")
	image = models.FileField(upload_to="images/", verbose_name="image")

	def __unicode__(self):
		return self.title

class Comment(models.Model):
	name = models.CharField(max_length=150, verbose_name="User")
	content = models.TextField(verbose_name="Comment")
	published = models.DateTimeField(verbose_name="Publication date")
	article = models.ForeignKey(Article)

	def __unicode__(self):
		return self.name

customhtml/models.py
#-*- coding: utf-8 -8-
from django.db import models

class CustomHtml(models.Model):
	title = models.CharField(max_length=150, verbose_name="Title")
	sourcehtml = models.TextField(verbose_name="HTML Code")

	def __unicode__(self):
		return self.title

notifications/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Notifications(models.Model):
	title = models.CharField(max_length=150, verbose_name="Title")
	content = models.TextField(verbose_name="Message")
	viewed = models.BooleanField(default=False, verbose_name="Open")
	user = models.ForeignKey(User)

	def __unicode__(self):
		return self.title

@receiver(post_save, sender=User)
def senb_welcome_message(sender, **kwargs):
	if kwargs.get('created', False):
		Notifications.objects.create(user=kwargs.get('instance'),
			title = "Welcome to out World",

			)

userprofile/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class UserProfile(models.Model):
	user = models.OneToOneField(User)
	country = models.CharField(max_length=150, verbose_name="Kraj")
	age = models.CharField(max_length=3, verbose_name="Wiek")

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

@receiver(post_save, sender=User)
def add_user_profile_on_user_created(sender, **kwargs):
	if kwargs.get('created',False):
		up = UserProfile.objects.create(user=kwargs.get('instance'))

articles/forms.py
from django import forms
from models import Comment

class CommentForm(forms.ModelForm):

	class Meta:
		model = Comment
		fields = ('name','content')

userprofile/forms.py
from django import forms
from models import UserProfile

class UserProfileForm(forms.ModelForm):

	class Meta:
		model = UserProfile
		fields = ('country','age')

articles/views.py
from django.shortcuts import render_to_response
from articles.models import Article, Comment
from forms import CommentForm
from django.core.context_processors import csrf
from django.utils import timezone
from django.http import HttpResponseRedirect

def articles(request):
	return render_to_response('articles.html',{'articles' : Article.objects.all()})

def article(request, article_id):
	return render_to_response('article.html',{'article': Article.objects.get(id=article_id)})

def add_comment(request,article_id):
	art = Article.objects.get(id=article_id)

	if request.method == "POST":
		cf = CommentForm(request.POST)
		if cf.is_valid():
			comment = cf.save(commit=False)
			comment.published = timezone.now()
			comment.article = art
			comment.save()

			return HttpResponseRedirect('/article/%s' % article_id)

	else:
		cf = CommentForm()

	args = {}
	args.update(csrf(request))
	args['article'] = art
	args['form'] = cf

	return render_to_response('add_comment.html', args)

customhtml/views.py
# Create your views here.

notifications/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from models import Notifications

def show_notification(request, notification_id):
	n = Notifications.objects.get(id=notification_id)
	return render_to_response('notification.html', {'notification':n})

def delete_notification(request, notification_id):
	n = Notifications.objects.get(id=notification_id)
	n.viewed = True
	n.save()

	return HttpResponseRedirect('/accounts/loggedin')

skcms/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.core.context_processors import csrf
from django.contrib.auth.forms import UserCreationForm
from notifications.models import Notifications

def login(request):
	c = {}
	c.update(csrf(request))
	return render_to_response('login.html', c)

def auth_view(request):
	username = request.POST.get('username','')
	password = request.POST.get('password','')
	user = auth.authenticate(username=username, password=password)

	if user is not None:
		auth.login(request,user)
		return HttpResponseRedirect('/accounts/loggedin/')
	else:
		return HttpResponseRedirect('/accounts/invalid/')

def loggedin(request):
	n = Notifications.objects.filter(user=request.user, viewed=False)
	return render_to_response('loggedin.html',{'user_name' : request.user.username, 'notifications': n})

def logout(request):
	auth.logout(request)
	return render_to_response('logout.html')

def invalid_login(request):
	return render_to_response('invalid_login.html')

def create_user(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/accounts/create_user_success/')

	args = {}
	args.update(csrf(request))
	args['form'] = UserCreationForm()

	return render_to_response('create_user.html', args)

def create_user_success(request):
	return render_to_response('create_user_success.html')

userprofile/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.core.context_processors import csrf
from forms import UserProfileForm
from django.contrib.auth.decorators import login_required

@login_required
def user_profile(request):
	if request.method == 'POST':
		form = UserProfileForm(request.POST, instance=request.user.profile)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/accounts/loggedin/')

	else:
		user = request.user
		profile = user.profile
		form = UserProfileForm(instance=profile)

	args = {}
	args.update(csrf(request))
	args['form'] = form

	return render_to_response('user_profile.html', args)

articles/templates/add_comment.html
{% extends "main.html" %}

{% block article %}

<form action="/article/{{ article.id }}/add_comment/" method="post" class="form horizontal well">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" class="btn btn-inverse" name="submit" value="Add comment" />
</form>

{% endblock %}

articles/templates/article.html
{% extends "main.html" %}

{% block article %}

					<h2>{{ article.title }}</h2>
                    <div class="article-info">
                        Opublikowano : {{ article.published }}
                    </div>
                    <img src="{{ article.image.url }}" class="article-img">
                    <div class="article-intro">
                        <p>{{ article.content }}</p>
                    </div>
                    <hr>
                    <h3>Komentarze</h3><!-- Komentarze -->
                    {% for c in article.comment_set.all %}
                    <div class="comment">
                        <p><span><em>{{ c.name }}</em></span></p>
                        <p><em>Opublikowano: {{ c.published }}</em></p>
                        <p>{{ c.content }}</p>
                    </div>
                    {%  endfor %}
                    <h4><a href="/article/{{ article.id }}/add_comment">Add comment</a></h4>

{% endblock %}

articles/templates/articles.html
{% extends "main.html" %}

{% block featured %}

{% for article in articles %}
<div class="span3 latest-article" id="first-art">
      <div class="latest-article-wrap">
          <a href="/article/{{ article.id }}/"><img src="{{ article.image.url }}" class="img-rounded"></a>
          <p>{{ article.content | truncatewords:11 }}</p>
         <a href="/article/{{ article.id }}/" class="label label-info pull-right">More</a>
            </div>
    </div>
{% endfor %}

{% endblock %}

{% block article %}

{% if articles.count > 0 %}				
{% for article in articles %}
				<div class="article"><!--  Article -->
                    <hr>
                    <h2><a href="/article/{{ article.id }}/">{{ article.title }}</a></h2>
                    <div class="article-info">
                        Publish : {{ article.published }}
                    </div>
                    <img src="{{ article.image.url }}" class="article-img img-rounded">
                    <div class="article-intro">
                        <p>{{ article.content | truncatewords:170 }}</p>
                    </div>
                    <a class="btn btn-inverse art-more" href="/article/{{ article.id }}/">More</a>
               </div>
{% endfor %}
{% else %}
<p>Lack of article</p>
{% endif %}

{% endblock %}

customhtml/templates/custom_html.html
<div class="custom-html">
{{ html.sourcehtml | safe }}
</div>

notifications/templates/notification.html
{% extends "main.html" %}

{% block article %}
<h3>{{ notification.title }}</h3>
<p>{{ notification.content }}</p>
<p><a href="/notifications/delete/{{ notification.id }}">CHECK THIS</a></p>
{% endblock %}

templates/create_user.html
{% extends "main.html" %}

{% block article %}
<h3>Rejestracja</h3>
<form action="/accounts/create_user/" method="post" class="form horizontal well">{% csrf_token %}
	{{ form }}
	<br>
	<input type="submit" class="btn btn-inverse" value="Zarejstruj"> 
</form>

{% endblock %}

templates/create_user_success.html
{% extends "main.html" %}

{% block article %}

<h3>Konto założone prawidłowo</h3>

{% endblock %}

templates/invalid_login.html
{% extends "main.html" %}

{% block article %}

<h3>Nieprawidłowy login</h3>
<a href="/accounts/login/">Spróbuj ponownie</a>

{% endblock %}

templates/loggedin.html
{% extends "main.html" %}

{% block article %}

<h3>Witaj: {{ user_name }}</h3>

{% if notifications.count > 0 %}

<h4>Powiadomienia</h4>

{%  for n in notifications %}
<p><a href="/notifications/show/{{n.id}}">{{ n.title }}</a></p>
{% endfor %}

{% endif %}

<p><a href="/accounts/logout/">Wyloguj się</a></p>
{% endblock %}

templates/login.html
{% extends "main.html" %}

{% block article %}

<form action="/accounts/auth/" method="post" class="form horizontal well">{% csrf_token %}
	<label for="username">Użytkownik:</label>
	<input type="text" name="username" value="" id="username">
	<label for="password">Hasło:</label>
	<input type="password" name="password" value="" id="password">
	<br>
	<input type="submit" class="btn btn-inverse" value="Zaloguj"> 
</form>

{% endblock %}

templates/logout.html
{% extends "main.html" %}

{% block article %}

<h3>Prawidłowe wylogowanie</h3>

{% endblock %}

templates/main.html
{% load static %}
{% load show_custom_html %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <title>Tytuł</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-responsive.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
 
<body>

<div class="container" id="wrapper">

    <div class="row"><!--  PASEK GORA -->
        <div class="topbar">
            <div class="logo pull-left">
                <h1><a href="#"><img src="{% static 'img/poziom.jpg' %}"></a></h1>
            </div>
            <div class="topbar-links pull-right">
                <a href="/accounts/login/">Logowanie</a> | <a href="/accounts/create_user/">Rejestracja</a>
            </div>
        </div>
    </div>

    <div class="row"><!-- Menu -->
        <div id="mainmenu" class="navbar navbar-inverse"> 
                <div class="navbar-inner">
                    <div>
                        <a class="brand" href="#">CMS</a>
                        <ul class="nav">
                            <li class="active"><a href="index.html">Start</a></li>
                            <li><a href="index.html">Artykuły</a></li>
                            <li><a href="index.html">Kontakt</a></li>
                        </ul>
                    </div>
                </div>
        </div>
    </div>

    <div class="row"><!-- Glowna czesc -->

        <div class="span9 left_col"><!-- Lewa kolumna -->
            <div  class="row latest"><!-- Najnowsze art -->

                {% block featured %}
                {% endblock %}

            </div><!--  Koniec najnowszych art -->

            <div class="row"><!-- Artykuly lista -->

                {% block article %}
                {% endblock %}

            </div><!--  Koniec listy art -->

        </div><!-- Koniec lewej kolumny -->

        <div class="span3"><!-- Prawa kolumna -->
            <div class="well sidebar-nav">
                <ul class="nav nav-list">
                    <li class="nav-header">Twoje konto</li>
                    <li class="active"><a href="/accounts/profile/">Ustawienia profilu</a></li>
                    <li><a href="">Powiadomienia</a></li>
                    <li><a href="/accounts/logout/">Wyloguj</a></li>
                </ul>
            </div>
        </div>

        <div class="span3"><!-- Prawa kolumna -->
            {% render_html 2 %}
        </div>


    </div>

    <div class="row">
        <hr>
        <div class="footer-wrap">
            {% render_html 1 %}
        </div>
    </div>

</div>

</body> 

</html>

userprofile/templates/user_profile.html
{% extends "main.html" %}

{% block article %}

<form action="/accounts/profile/" method="post" class="form horizontal well">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" class="btn btn-inverse" value="Refresh">
</form>

{% endblock %}